import domToImage from 'dom-to-image';
import jsPDF from 'jspdf';
import moment from 'moment';
import {
  Component,
  ViewChild,
  ElementRef,
  OnInit,
  AfterViewInit,
  OnChanges,
  DoCheck,
  AfterViewChecked, ViewChildren, QueryList
} from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { MatCardModule } from "@angular/material/card";
import { MatTableModule } from "@angular/material/table";

import html2canvas from 'html2canvas';
import {HttpClient} from "@angular/common/http";
import {MatButton} from "@angular/material/button";
export interface PeriodicElement {
  setPoints: string;
  deviation: string;
  uncertainty: string;
}

const ELEMENT_DATA: PeriodicElement[] = [
  {setPoints: '+60 °C', deviation: '.5 °C', uncertainty: '±0.2 °C'},
  {setPoints: '+25 °C', deviation: '.5 °C', uncertainty: '±0.2 °C'},
  {setPoints: '0 °C', deviation: '.5 °C', uncertainty: '±0.2 °C'},
  {setPoints: '-10 °C', deviation: '.5 °C', uncertainty: '±0.2 °C'},
  {setPoints: '-30 °C', deviation: '.5 °C', uncertainty: '±0.2 °C'},
];

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, MatCardModule, MatTableModule, MatButton],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent implements AfterViewInit {
  instrumentName: string = 'Test Instrument';
  title = 'lisaline';
  displayedColumns: string[] = ['setPoints', 'deviation', 'uncertainty'];
  dataSource = ELEMENT_DATA;
  showAll: boolean = true;
  names: any[] = [
    {name: 'Test Instrument 1', id: 1},
    {name: 'Test Instrument 2', id: Math.random() * 12},
    {name: 'Test Instrument 3', id: Math.random() * 12},
    {name: 'Test Instrument 4', id: Math.random() * 12},
    {name: 'Test Instrument 5', id: Math.random() * 12},
    {name: 'Test Instrument 6', id: Math.random() * 12},
    {name: 'Test Instrument 7', id: Math.random() * 12},
    {name: 'Test Instrument 8', id: Math.random() * 12},
    {name: 'Test Instrument 9', id: Math.random() * 12},
    {name: 'Test Instrument 10', id: Math.random() * 12},
    {name: 'Test Instrument 11', id: Math.random() * 12},
    {name: 'Test Instrument 12', id: Math.random() * 12},
    {name: 'Test Instrument 13', id: Math.random() * 12},
    {name: 'Test Instrument 14', id: Math.random() * 12},
    {name: 'Test Instrument 15', id: Math.random() * 12},
    {name: 'Test Instrument 16', id: Math.random() * 12},
    {name: 'Test Instrument 17', id: Math.random() * 12},
    {name: 'Test Instrument 18', id: Math.random() * 12},
    {name: 'Test Instrument 19', id: Math.random() * 12},
    {name: 'Test Instrument 20', id: Math.random() * 12},
    {name: 'Test Instrument 1', id: Math.random() * 12},
    {name: 'Test Instrument 2', id: Math.random() * 12},
    {name: 'Test Instrument 3', id: Math.random() * 12},
    {name: 'Test Instrument 4', id: Math.random() * 12},
    {name: 'Test Instrument 5', id: Math.random() * 12},
    {name: 'Test Instrument 6', id: Math.random() * 12},
    {name: 'Test Instrument 7', id: Math.random() * 12},
    {name: 'Test Instrument 8', id: Math.random() * 12},
    {name: 'Test Instrument 9', id: Math.random() * 12},
    {name: 'Test Instrument 10', id: Math.random() * 12},
    {name: 'Test Instrument 11', id: Math.random() * 12},
    {name: 'Test Instrument 12', id: Math.random() * 12},
    {name: 'Test Instrument 13', id: Math.random() * 12},
    {name: 'Test Instrument 14', id: Math.random() * 12},
    {name: 'Test Instrument 15', id: Math.random() * 12},
    {name: 'Test Instrument 16', id: Math.random() * 12},
    {name: 'Test Instrument 17', id: Math.random() * 12},
    {name: 'Test Instrument 18', id: Math.random() * 12},
    {name: 'Test Instrument 19', id: Math.random() * 12},
    {name: 'Test Instrument 20', id: Math.random() * 12},
    {name: 'Test Instrument 1', id: Math.random() * 12},
    {name: 'Test Instrument 2', id: Math.random() * 12},
    {name: 'Test Instrument 3', id: Math.random() * 12},
    {name: 'Test Instrument 4', id: Math.random() * 12},
    {name: 'Test Instrument 5', id: Math.random() * 12},
    {name: 'Test Instrument 6', id: Math.random() * 12},
    {name: 'Test Instrument 7', id: Math.random() * 12},
    {name: 'Test Instrument 8', id: Math.random() * 12},
    {name: 'Test Instrument 9', id: Math.random() * 12},
    {name: 'Test Instrument 10', id: Math.random() * 12},
    {name: 'Test Instrument 11', id: Math.random() * 12},
    {name: 'Test Instrument 12', id: Math.random() * 12},
    {name: 'Test Instrument 13', id: Math.random() * 12},
    {name: 'Test Instrument 14', id: Math.random() * 12},
    {name: 'Test Instrument 15', id: Math.random() * 12},
    {name: 'Test Instrument 16', id: Math.random() * 12},
    {name: 'Test Instrument 17', id: Math.random() * 12},
    {name: 'Test Instrument 18', id: Math.random() * 12},
    {name: 'Test Instrument 19', id: Math.random() * 12},
    {name: 'Test Instrument 20', id: Math.random() * 12},{name: 'Test Instrument 1', id: Math.random() * 12},
    {name: 'Test Instrument 2', id: Math.random() * 12},
    {name: 'Test Instrument 3', id: Math.random() * 12},
    {name: 'Test Instrument 4', id: Math.random() * 12},
    {name: 'Test Instrument 5', id: Math.random() * 12},
    {name: 'Test Instrument 6', id: Math.random() * 12},
    {name: 'Test Instrument 7', id: Math.random() * 12},
    {name: 'Test Instrument 8', id: Math.random() * 12},
    {name: 'Test Instrument 9', id: Math.random() * 12},
    {name: 'Test Instrument 10', id: Math.random() * 12},
    {name: 'Test Instrument 11', id: Math.random() * 12},
    {name: 'Test Instrument 12', id: Math.random() * 12},
    {name: 'Test Instrument 13', id: Math.random() * 12},
    {name: 'Test Instrument 14', id: Math.random() * 12},
    {name: 'Test Instrument 15', id: Math.random() * 12},
    {name: 'Test Instrument 16', id: Math.random() * 12},
    {name: 'Test Instrument 17', id: Math.random() * 12},
    {name: 'Test Instrument 18', id: Math.random() * 12},
    {name: 'Test Instrument 19', id: Math.random() * 12},
    {name: 'Test Instrument 20', id: Math.random() * 12},
    {name: 'Test Instrument 1', id: Math.random() * 12},
    {name: 'Test Instrument 2', id: Math.random() * 12},
    {name: 'Test Instrument 3', id: Math.random() * 12},
    {name: 'Test Instrument 4', id: Math.random() * 12},
    {name: 'Test Instrument 5', id: Math.random() * 12},
    {name: 'Test Instrument 6', id: Math.random() * 12},
    {name: 'Test Instrument 7', id: Math.random() * 12},
    {name: 'Test Instrument 8', id: Math.random() * 12},
    {name: 'Test Instrument 9', id: Math.random() * 12},
    {name: 'Test Instrument 10', id: Math.random() * 12},
    {name: 'Test Instrument 11', id: Math.random() * 12},
    {name: 'Test Instrument 12', id: Math.random() * 12},
    {name: 'Test Instrument 13', id: Math.random() * 12},
    {name: 'Test Instrument 14', id: Math.random() * 12},
    {name: 'Test Instrument 15', id: Math.random() * 12},
    {name: 'Test Instrument 16', id: Math.random() * 12},
    {name: 'Test Instrument 17', id: Math.random() * 12},
    {name: 'Test Instrument 18', id: Math.random() * 12},
    {name: 'Test Instrument 19', id: Math.random() * 12},
    {name: 'Test Instrument 20', id: Math.random() * 12},
    {name: 'Test Instrument 1', id: Math.random() * 12},
    {name: 'Test Instrument 2', id: Math.random() * 12},
    {name: 'Test Instrument 3', id: Math.random() * 12},
    {name: 'Test Instrument 4', id: Math.random() * 12},
    {name: 'Test Instrument 5', id: Math.random() * 12},
    {name: 'Test Instrument 6', id: Math.random() * 12},
    {name: 'Test Instrument 7', id: Math.random() * 12},
    {name: 'Test Instrument 8', id: Math.random() * 12},
    {name: 'Test Instrument 9', id: Math.random() * 12},
    {name: 'Test Instrument 10', id: Math.random() * 12},
    {name: 'Test Instrument 11', id: Math.random() * 12},
    {name: 'Test Instrument 12', id: Math.random() * 12},
    {name: 'Test Instrument 13', id: Math.random() * 12},
    {name: 'Test Instrument 14', id: Math.random() * 12},
    {name: 'Test Instrument 15', id: Math.random() * 12},
    {name: 'Test Instrument 16', id: Math.random() * 12},
    {name: 'Test Instrument 17', id: Math.random() * 12},
    {name: 'Test Instrument 18', id: Math.random() * 12},
    {name: 'Test Instrument 19', id: Math.random() * 12},
    {name: 'Test Instrument 20', id: Math.random() * 12},
    {name: 'Test Instrument 1', id: Math.random() * 12},
    {name: 'Test Instrument 2', id: Math.random() * 12},
    {name: 'Test Instrument 3', id: Math.random() * 12},
    {name: 'Test Instrument 4', id: Math.random() * 12},
    {name: 'Test Instrument 5', id: Math.random() * 12},
    {name: 'Test Instrument 6', id: Math.random() * 12},
    {name: 'Test Instrument 7', id: Math.random() * 12},
    {name: 'Test Instrument 8', id: Math.random() * 12},
    {name: 'Test Instrument 9', id: Math.random() * 12},
    {name: 'Test Instrument 10', id: Math.random() * 12},
    {name: 'Test Instrument 11', id: Math.random() * 12},
    {name: 'Test Instrument 12', id: Math.random() * 12},
    {name: 'Test Instrument 13', id: Math.random() * 12},
    {name: 'Test Instrument 14', id: Math.random() * 12},
    {name: 'Test Instrument 15', id: Math.random() * 12},
    {name: 'Test Instrument 16', id: Math.random() * 12},
    {name: 'Test Instrument 17', id: Math.random() * 12},
    {name: 'Test Instrument 18', id: Math.random() * 12},
    {name: 'Test Instrument 19', id: Math.random() * 12},
    {name: 'Test Instrument 20', id: Math.random() * 12},{name: 'Test Instrument 1', id: Math.random() * 12},
    {name: 'Test Instrument 2', id: Math.random() * 12},
    {name: 'Test Instrument 3', id: Math.random() * 12},
    {name: 'Test Instrument 4', id: Math.random() * 12},
    {name: 'Test Instrument 5', id: Math.random() * 12},
    {name: 'Test Instrument 6', id: Math.random() * 12},
    {name: 'Test Instrument 7', id: Math.random() * 12},
    {name: 'Test Instrument 8', id: Math.random() * 12},
    {name: 'Test Instrument 9', id: Math.random() * 12},
    {name: 'Test Instrument 10', id: Math.random() * 12},
    {name: 'Test Instrument 11', id: Math.random() * 12},
    {name: 'Test Instrument 12', id: Math.random() * 12},
    {name: 'Test Instrument 13', id: Math.random() * 12},
    {name: 'Test Instrument 14', id: Math.random() * 12},
    {name: 'Test Instrument 15', id: Math.random() * 12},
    {name: 'Test Instrument 16', id: Math.random() * 12},
    {name: 'Test Instrument 17', id: Math.random() * 12},
    {name: 'Test Instrument 18', id: Math.random() * 12},
    {name: 'Test Instrument 19', id: Math.random() * 12},
    {name: 'Test Instrument 20', id: Math.random() * 12},
    {name: 'Test Instrument 1', id: Math.random() * 12},
    {name: 'Test Instrument 2', id: Math.random() * 12},
    {name: 'Test Instrument 3', id: Math.random() * 12},
    {name: 'Test Instrument 4', id: Math.random() * 12},
    {name: 'Test Instrument 5', id: Math.random() * 12},
    {name: 'Test Instrument 6', id: Math.random() * 12},
    {name: 'Test Instrument 7', id: Math.random() * 12},
    {name: 'Test Instrument 8', id: Math.random() * 12},
    {name: 'Test Instrument 9', id: Math.random() * 12},
    {name: 'Test Instrument 10', id: Math.random() * 12},
    {name: 'Test Instrument 11', id: Math.random() * 12},
    {name: 'Test Instrument 12', id: Math.random() * 12},
    {name: 'Test Instrument 13', id: Math.random() * 12},
    {name: 'Test Instrument 14', id: Math.random() * 12},
    {name: 'Test Instrument 15', id: Math.random() * 12},
    {name: 'Test Instrument 16', id: Math.random() * 12},
    {name: 'Test Instrument 17', id: Math.random() * 12},
    {name: 'Test Instrument 18', id: Math.random() * 12},
    {name: 'Test Instrument 19', id: Math.random() * 12},
    {name: 'Test Instrument 20', id: Math.random() * 12},{name: 'Test Instrument 1', id: Math.random() * 12},
    {name: 'Test Instrument 2', id: Math.random() * 12},
    {name: 'Test Instrument 3', id: Math.random() * 12},
    {name: 'Test Instrument 4', id: Math.random() * 12},
    {name: 'Test Instrument 5', id: Math.random() * 12},
    {name: 'Test Instrument 6', id: Math.random() * 12},
    {name: 'Test Instrument 7', id: Math.random() * 12},
    {name: 'Test Instrument 8', id: Math.random() * 12},
    {name: 'Test Instrument 9', id: Math.random() * 12},
    {name: 'Test Instrument 10', id: Math.random() * 12},
    {name: 'Test Instrument 11', id: Math.random() * 12},
    {name: 'Test Instrument 12', id: Math.random() * 12},
    {name: 'Test Instrument 13', id: Math.random() * 12},
    {name: 'Test Instrument 14', id: Math.random() * 12},
    {name: 'Test Instrument 15', id: Math.random() * 12},
    {name: 'Test Instrument 16', id: Math.random() * 12},
    {name: 'Test Instrument 17', id: Math.random() * 12},
    {name: 'Test Instrument 18', id: Math.random() * 12},
    {name: 'Test Instrument 19', id: Math.random() * 12},
    {name: 'Test Instrument 20', id: Math.random() * 12},
    {name: 'Test Instrument 1', id: Math.random() * 12},
    {name: 'Test Instrument 2', id: Math.random() * 12},
    {name: 'Test Instrument 3', id: Math.random() * 12},
    {name: 'Test Instrument 4', id: Math.random() * 12},
    {name: 'Test Instrument 5', id: Math.random() * 12},
    {name: 'Test Instrument 6', id: Math.random() * 12},
    {name: 'Test Instrument 7', id: Math.random() * 12},
    {name: 'Test Instrument 8', id: Math.random() * 12},
    {name: 'Test Instrument 9', id: Math.random() * 12},
    {name: 'Test Instrument 10', id: Math.random() * 12},
    {name: 'Test Instrument 11', id: Math.random() * 12},
    {name: 'Test Instrument 12', id: Math.random() * 12},
    {name: 'Test Instrument 13', id: Math.random() * 12},
    {name: 'Test Instrument 14', id: Math.random() * 12},
    {name: 'Test Instrument 15', id: Math.random() * 12},
    {name: 'Test Instrument 16', id: Math.random() * 12},
    {name: 'Test Instrument 17', id: Math.random() * 12},
    {name: 'Test Instrument 18', id: Math.random() * 12},
    {name: 'Test Instrument 19', id: Math.random() * 12},
    {name: 'Test Instrument 20', id: Math.random() * 12},{name: 'Test Instrument 1', id: Math.random() * 12},
    {name: 'Test Instrument 2', id: Math.random() * 12},
    {name: 'Test Instrument 3', id: Math.random() * 12},
    {name: 'Test Instrument 4', id: Math.random() * 12},
    {name: 'Test Instrument 5', id: Math.random() * 12},
    {name: 'Test Instrument 6', id: Math.random() * 12},
    {name: 'Test Instrument 7', id: Math.random() * 12},
    {name: 'Test Instrument 8', id: Math.random() * 12},
    {name: 'Test Instrument 9', id: Math.random() * 12},
    {name: 'Test Instrument 10', id: Math.random() * 12},
    {name: 'Test Instrument 11', id: Math.random() * 12},
    {name: 'Test Instrument 12', id: Math.random() * 12},
    {name: 'Test Instrument 13', id: Math.random() * 12},
    {name: 'Test Instrument 14', id: Math.random() * 12},
    {name: 'Test Instrument 15', id: Math.random() * 12},
    {name: 'Test Instrument 16', id: Math.random() * 12},
    {name: 'Test Instrument 17', id: Math.random() * 12},
    {name: 'Test Instrument 18', id: Math.random() * 12},
    {name: 'Test Instrument 19', id: Math.random() * 12},
    {name: 'Test Instrument 20', id: Math.random() * 12},
    {name: 'Test Instrument 1', id: Math.random() * 12},
    {name: 'Test Instrument 2', id: Math.random() * 12},
    {name: 'Test Instrument 3', id: Math.random() * 12},
    {name: 'Test Instrument 4', id: Math.random() * 12},
    {name: 'Test Instrument 5', id: Math.random() * 12},
    {name: 'Test Instrument 6', id: Math.random() * 12},
    {name: 'Test Instrument 7', id: Math.random() * 12},
    {name: 'Test Instrument 8', id: Math.random() * 12},
    {name: 'Test Instrument 9', id: Math.random() * 12},
    {name: 'Test Instrument 10', id: Math.random() * 12},
    {name: 'Test Instrument 11', id: Math.random() * 12},
    {name: 'Test Instrument 12', id: Math.random() * 12},
    {name: 'Test Instrument 13', id: Math.random() * 12},
    {name: 'Test Instrument 14', id: Math.random() * 12},
    {name: 'Test Instrument 15', id: Math.random() * 12},
    {name: 'Test Instrument 16', id: Math.random() * 12},
    {name: 'Test Instrument 17', id: Math.random() * 12},
    {name: 'Test Instrument 18', id: Math.random() * 12},
    {name: 'Test Instrument 19', id: Math.random() * 12},
    {name: 'Test Instrument 20', id: Math.random() * 12},
    {name: 'Test Instrument 1', id: Math.random() * 12},
    {name: 'Test Instrument 2', id: Math.random() * 12},
    {name: 'Test Instrument 3', id: Math.random() * 12},
    {name: 'Test Instrument 4', id: Math.random() * 12},
    {name: 'Test Instrument 5', id: Math.random() * 12},
    {name: 'Test Instrument 6', id: Math.random() * 12},
    {name: 'Test Instrument 7', id: Math.random() * 12},
    {name: 'Test Instrument 8', id: Math.random() * 12},
    {name: 'Test Instrument 9', id: Math.random() * 12},
    {name: 'Test Instrument 10', id: Math.random() * 12},
    {name: 'Test Instrument 11', id: Math.random() * 12},
    {name: 'Test Instrument 12', id: Math.random() * 12},
    {name: 'Test Instrument 13', id: Math.random() * 12},
    {name: 'Test Instrument 14', id: Math.random() * 12},
    {name: 'Test Instrument 15', id: Math.random() * 12},
    {name: 'Test Instrument 16', id: Math.random() * 12},
    {name: 'Test Instrument 17', id: Math.random() * 12},
    {name: 'Test Instrument 18', id: Math.random() * 12},
    {name: 'Test Instrument 19', id: Math.random() * 12},
    {name: 'Test Instrument 20', id: Math.random() * 12},
    {name: 'Test Instrument 1', id: Math.random() * 12},
    {name: 'Test Instrument 2', id: Math.random() * 12},
    {name: 'Test Instrument 3', id: Math.random() * 12},
    {name: 'Test Instrument 4', id: Math.random() * 12},
    {name: 'Test Instrument 5', id: Math.random() * 12},
    {name: 'Test Instrument 6', id: Math.random() * 12},
    {name: 'Test Instrument 7', id: Math.random() * 12},
    {name: 'Test Instrument 8', id: Math.random() * 12},
    {name: 'Test Instrument 9', id: Math.random() * 12},
    {name: 'Test Instrument 10', id: Math.random() * 12},
    {name: 'Test Instrument 11', id: Math.random() * 12},
    {name: 'Test Instrument 12', id: Math.random() * 12},
    {name: 'Test Instrument 13', id: Math.random() * 12},
    {name: 'Test Instrument 14', id: Math.random() * 12},
    {name: 'Test Instrument 15', id: Math.random() * 12},
    {name: 'Test Instrument 16', id: Math.random() * 12},
    {name: 'Test Instrument 17', id: Math.random() * 12},
    {name: 'Test Instrument 18', id: Math.random() * 12},
    {name: 'Test Instrument 19', id: Math.random() * 12},
    {name: 'Test Instrument 20', id: Math.random() * 12},{name: 'Test Instrument 1', id: Math.random() * 12},
    {name: 'Test Instrument 2', id: Math.random() * 12},
    {name: 'Test Instrument 3', id: Math.random() * 12},
    {name: 'Test Instrument 4', id: Math.random() * 12},
    {name: 'Test Instrument 5', id: Math.random() * 12},
    {name: 'Test Instrument 6', id: Math.random() * 12},
    {name: 'Test Instrument 7', id: Math.random() * 12},
    {name: 'Test Instrument 8', id: Math.random() * 12},
    {name: 'Test Instrument 9', id: Math.random() * 12},
    {name: 'Test Instrument 10', id: Math.random() * 12},
    {name: 'Test Instrument 11', id: Math.random() * 12},
    {name: 'Test Instrument 12', id: Math.random() * 12},
    {name: 'Test Instrument 13', id: Math.random() * 12},
    {name: 'Test Instrument 14', id: Math.random() * 12},
    {name: 'Test Instrument 15', id: Math.random() * 12},
    {name: 'Test Instrument 16', id: Math.random() * 12},
    {name: 'Test Instrument 17', id: Math.random() * 12},
    {name: 'Test Instrument 18', id: Math.random() * 12},
    {name: 'Test Instrument 19', id: Math.random() * 12},
    {name: 'Test Instrument 20', id: Math.random() * 12},
    {name: 'Test Instrument 1', id: Math.random() * 12},
    {name: 'Test Instrument 2', id: Math.random() * 12},
    {name: 'Test Instrument 3', id: Math.random() * 12},
    {name: 'Test Instrument 4', id: Math.random() * 12},
    {name: 'Test Instrument 5', id: Math.random() * 12},
    {name: 'Test Instrument 6', id: Math.random() * 12},
    {name: 'Test Instrument 7', id: Math.random() * 12},
    {name: 'Test Instrument 8', id: Math.random() * 12},
    {name: 'Test Instrument 9', id: Math.random() * 12},
    {name: 'Test Instrument 10', id: Math.random() * 12},
    {name: 'Test Instrument 11', id: Math.random() * 12},
    {name: 'Test Instrument 12', id: Math.random() * 12},
    {name: 'Test Instrument 13', id: Math.random() * 12},
    {name: 'Test Instrument 14', id: Math.random() * 12},
    {name: 'Test Instrument 15', id: Math.random() * 12},
    {name: 'Test Instrument 16', id: Math.random() * 12},
    {name: 'Test Instrument 17', id: Math.random() * 12},
    {name: 'Test Instrument 18', id: Math.random() * 12},
    {name: 'Test Instrument 19', id: Math.random() * 12},
    {name: 'Test Instrument 20', id: Math.random() * 12},
    {name: 'Test Instrument 1', id: Math.random() * 12},
    {name: 'Test Instrument 2', id: Math.random() * 12},
    {name: 'Test Instrument 3', id: Math.random() * 12},
    {name: 'Test Instrument 4', id: Math.random() * 12},
    {name: 'Test Instrument 5', id: Math.random() * 12},
    {name: 'Test Instrument 6', id: Math.random() * 12},
    {name: 'Test Instrument 7', id: Math.random() * 12},
    {name: 'Test Instrument 8', id: Math.random() * 12},
    {name: 'Test Instrument 9', id: Math.random() * 12},
    {name: 'Test Instrument 10', id: Math.random() * 12},
    {name: 'Test Instrument 11', id: Math.random() * 12},
    {name: 'Test Instrument 12', id: Math.random() * 12},
    {name: 'Test Instrument 13', id: Math.random() * 12},
    {name: 'Test Instrument 14', id: Math.random() * 12},
    {name: 'Test Instrument 15', id: Math.random() * 12},
    {name: 'Test Instrument 16', id: Math.random() * 12},
    {name: 'Test Instrument 17', id: Math.random() * 12},
    {name: 'Test Instrument 18', id: Math.random() * 12},
    {name: 'Test Instrument 19', id: Math.random() * 12},
    {name: 'Test Instrument 20', id: Math.random() * 12},
    {name: 'Test Instrument 1', id: Math.random() * 12},
    {name: 'Test Instrument 2', id: Math.random() * 12},
    {name: 'Test Instrument 3', id: Math.random() * 12},
    {name: 'Test Instrument 4', id: Math.random() * 12},
    {name: 'Test Instrument 5', id: Math.random() * 12},
    {name: 'Test Instrument 6', id: Math.random() * 12},
    {name: 'Test Instrument 7', id: Math.random() * 12},
    {name: 'Test Instrument 8', id: Math.random() * 12},
    {name: 'Test Instrument 9', id: Math.random() * 12},
    {name: 'Test Instrument 10', id: Math.random() * 12},
    {name: 'Test Instrument 11', id: Math.random() * 12},
    {name: 'Test Instrument 12', id: Math.random() * 12},
    {name: 'Test Instrument 13', id: Math.random() * 12},
    {name: 'Test Instrument 14', id: Math.random() * 12},
    {name: 'Test Instrument 15', id: Math.random() * 12},
    {name: 'Test Instrument 16', id: Math.random() * 12},
    {name: 'Test Instrument 17', id: Math.random() * 12},
    {name: 'Test Instrument 18', id: Math.random() * 12},
    {name: 'Test Instrument 19', id: Math.random() * 12},
    {name: 'Test Instrument 20', id: Math.random() * 12},{name: 'Test Instrument 1', id: Math.random() * 12},
    {name: 'Test Instrument 2', id: Math.random() * 12},
    {name: 'Test Instrument 3', id: Math.random() * 12},
    {name: 'Test Instrument 4', id: Math.random() * 12},
    {name: 'Test Instrument 5', id: Math.random() * 12},
    {name: 'Test Instrument 6', id: Math.random() * 12},
    {name: 'Test Instrument 7', id: Math.random() * 12},
    {name: 'Test Instrument 8', id: Math.random() * 12},
    {name: 'Test Instrument 9', id: Math.random() * 12},
    {name: 'Test Instrument 10', id: Math.random() * 12},
    {name: 'Test Instrument 11', id: Math.random() * 12},
    {name: 'Test Instrument 12', id: Math.random() * 12},
    {name: 'Test Instrument 13', id: Math.random() * 12},
    {name: 'Test Instrument 14', id: Math.random() * 12},
    {name: 'Test Instrument 15', id: Math.random() * 12},
    {name: 'Test Instrument 16', id: Math.random() * 12},
    {name: 'Test Instrument 17', id: Math.random() * 12},
    {name: 'Test Instrument 18', id: Math.random() * 12},
    {name: 'Test Instrument 19', id: Math.random() * 12},
    {name: 'Test Instrument 20', id: Math.random() * 12},
    {name: 'Test Instrument 1', id: Math.random() * 12},
    {name: 'Test Instrument 2', id: Math.random() * 12},
    {name: 'Test Instrument 3', id: Math.random() * 12},
    {name: 'Test Instrument 4', id: Math.random() * 12},
    {name: 'Test Instrument 5', id: Math.random() * 12},
    {name: 'Test Instrument 6', id: Math.random() * 12},
    {name: 'Test Instrument 7', id: Math.random() * 12},
    {name: 'Test Instrument 8', id: Math.random() * 12},
    {name: 'Test Instrument 9', id: Math.random() * 12},
    {name: 'Test Instrument 10', id: Math.random() * 12},
    {name: 'Test Instrument 11', id: Math.random() * 12},
    {name: 'Test Instrument 12', id: Math.random() * 12},
    {name: 'Test Instrument 13', id: Math.random() * 12},
    {name: 'Test Instrument 14', id: Math.random() * 12},
    {name: 'Test Instrument 15', id: Math.random() * 12},
    {name: 'Test Instrument 16', id: Math.random() * 12},
    {name: 'Test Instrument 17', id: Math.random() * 12},
    {name: 'Test Instrument 18', id: Math.random() * 12},
    {name: 'Test Instrument 19', id: Math.random() * 12},
    {name: 'Test Instrument 20', id: Math.random() * 12},{name: 'Test Instrument 1', id: Math.random() * 12},
    {name: 'Test Instrument 2', id: Math.random() * 12},
    {name: 'Test Instrument 3', id: Math.random() * 12},
    {name: 'Test Instrument 4', id: Math.random() * 12},
    {name: 'Test Instrument 5', id: Math.random() * 12},
    {name: 'Test Instrument 6', id: Math.random() * 12},
    {name: 'Test Instrument 7', id: Math.random() * 12},
    {name: 'Test Instrument 8', id: Math.random() * 12},
    {name: 'Test Instrument 9', id: Math.random() * 12},
    {name: 'Test Instrument 10', id: Math.random() * 12},
    {name: 'Test Instrument 11', id: Math.random() * 12},
    {name: 'Test Instrument 12', id: Math.random() * 12},
    {name: 'Test Instrument 13', id: Math.random() * 12},
    {name: 'Test Instrument 14', id: Math.random() * 12},
    {name: 'Test Instrument 15', id: Math.random() * 12},
    {name: 'Test Instrument 16', id: Math.random() * 12},
    {name: 'Test Instrument 17', id: Math.random() * 12},
    {name: 'Test Instrument 18', id: Math.random() * 12},
    {name: 'Test Instrument 19', id: Math.random() * 12},
    {name: 'Test Instrument 20', id: Math.random() * 12},
    {name: 'Test Instrument 1', id: Math.random() * 12},
    {name: 'Test Instrument 2', id: Math.random() * 12},
    {name: 'Test Instrument 3', id: Math.random() * 12},
    {name: 'Test Instrument 4', id: Math.random() * 12},
    {name: 'Test Instrument 5', id: Math.random() * 12},
    {name: 'Test Instrument 6', id: Math.random() * 12},
    {name: 'Test Instrument 7', id: Math.random() * 12},
    {name: 'Test Instrument 8', id: Math.random() * 12},
    {name: 'Test Instrument 9', id: Math.random() * 12},
    {name: 'Test Instrument 10', id: Math.random() * 12},
    {name: 'Test Instrument 11', id: Math.random() * 12},
    {name: 'Test Instrument 12', id: Math.random() * 12},
    {name: 'Test Instrument 13', id: Math.random() * 12},
    {name: 'Test Instrument 14', id: Math.random() * 12},
    {name: 'Test Instrument 15', id: Math.random() * 12},
    {name: 'Test Instrument 16', id: Math.random() * 12},
    {name: 'Test Instrument 17', id: Math.random() * 12},
    {name: 'Test Instrument 18', id: Math.random() * 12},
    {name: 'Test Instrument 19', id: Math.random() * 12},
    {name: 'Test Instrument 20', id: Math.random() * 12},{name: 'Test Instrument 1', id: Math.random() * 12},
    {name: 'Test Instrument 2', id: Math.random() * 12},
    {name: 'Test Instrument 3', id: Math.random() * 12},
    {name: 'Test Instrument 4', id: Math.random() * 12},
    {name: 'Test Instrument 5', id: Math.random() * 12},
    {name: 'Test Instrument 6', id: Math.random() * 12},
    {name: 'Test Instrument 7', id: Math.random() * 12},
    {name: 'Test Instrument 8', id: Math.random() * 12},
    {name: 'Test Instrument 9', id: Math.random() * 12},
    {name: 'Test Instrument 10', id: Math.random() * 12},
    {name: 'Test Instrument 11', id: Math.random() * 12},
    {name: 'Test Instrument 12', id: Math.random() * 12},
    {name: 'Test Instrument 13', id: Math.random() * 12},
    {name: 'Test Instrument 14', id: Math.random() * 12},
    {name: 'Test Instrument 15', id: Math.random() * 12},
    {name: 'Test Instrument 16', id: Math.random() * 12},
    {name: 'Test Instrument 17', id: Math.random() * 12},
    {name: 'Test Instrument 18', id: Math.random() * 12},
    {name: 'Test Instrument 19', id: Math.random() * 12},
    {name: 'Test Instrument 20', id: Math.random() * 12},




  ];
  testNativeElements: HTMLElement[] = [];
  @ViewChildren('dataToExport') dataToExport: QueryList<any> = new QueryList<any>();

  constructor(private http: HttpClient) { }

  ngAfterViewInit() {
    this.dataToExport.forEach((element: ElementRef) => {
      this.testNativeElements.push(element.nativeElement as HTMLElement);
    })
    console.log(this.testNativeElements);
  }

  public async generateCertificate() {
    this.showAll = false;
      for (const element of this.testNativeElements) {
        const canvas = await html2canvas(element, {scale: 5})
        const pdf = new jsPDF('p', 'mm', 'a4');
        let width = pdf.internal.pageSize.getWidth();
        let height = pdf.internal.pageSize.getHeight();
        canvas.toDataURL('image/jpeg');
        let result = pdf.addImage(canvas, 'JPEG', 0, 0, width, height);
        let output = pdf.output('blob');
        console.log(output);
        result.save('test.pdf');
      }

    // this.testNativeElements.forEach((element: ElementRef, index) => {
        // const testtest= html2canvas(element.nativeElement as HTMLElement, {scale: 5});
        // html2canvas(element.nativeElement as HTMLElement, {scale: 5}).then((canvas) => {
        //   const pdf = new jsPDF('p', 'mm', 'a4');
        //   let width = pdf.internal.pageSize.getWidth();
        //   let height = pdf.internal.pageSize.getHeight();
        //   const imgData = canvas.toDataURL('image/jpeg');
        //   let result = pdf.addImage(imgData, 'JPEG', 0, 0, width, height);
        //   // console.log(result);
        //   // result.save('test.pdf');
        //   let output = pdf.output('blob');
        //   console.log(output);
        //   this.testAllPDS.push(output);
        // })
      // })
  }



  uploadFiles(event: any) {
    const file: File = event.target?.files[0];
    console.log(file);


    let form = new FormData();
    form.append(`master_certificate`, file);
    console.log(form);
    this.http.post('http://localhost:3000/api/batch/pdf', form, {

    }).subscribe((data) => {
      console.log(data);
    })
  }
}
